<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobApplication.Domain\JobApplication.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Applications\" />
    <Folder Include="Features\Jobs\" />
    <Folder Include="Features\Auth\" />
  </ItemGroup>

</Project>
